--- # Demo of the copy module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Example of future command with AT module
    at: command="ls -la /var/log > /home/ansible/at.log" count=1 units="minutes"
