--- # Demo of the fetch module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  tasks:
  - name: Copy Remote host file to local
    fetch: src=/etc/hosts dest=/home/ansible/prefix-{{ ansible_hostname }} flat=yes
