--- # Demo of the filesystem module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Format remote data partition
    filesystem: fstype=ext3 dev=/dev/svdf1 opts="-cc"
