--- # Demo of the HTPasswd module
- hosts: deb
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install apache
    apt: name=apache2 state=latest
  - name: adding user to website authentication
    htpasswd: path=/etc/apache2/.htpasswd name=test passwd=test owner=<user> group=<group> mode=0640
