--- # Demo of the SELinux module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Changing SELinux config to permissive
    selinux: policy=targeted state=permissive
