--- # Demo of the stat module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Does a file/dir in a path exist?
    stat: path=/home/ansible/abc
    register: p
  - debug: msg="The path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir
