--- # Demo of the unarchive module
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Copy and unarchive a file
    unarchive: src=test.tar.gz dest=/home/ansible/unarchive
