--- # When playbook - conditionals
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  vars:
    playbook_type: conditionalexample
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  tasks:
    - name: Install Apache appropriate to distribution type Deb/Ubuntu
      command: apt-get -y remove apache2
      when: ansible_os_family == "Debian"
    - name: Install Apache appropriate to RH/CentOS
      command: yum -y remove httpd
      when: ansible_os_family == "RedHat"
