--- # Error handling
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Execute a fail
    command: /bin/false
    ignore_errors: yes
  - name: Install lynx
    yum: pkg=lynx state=removed
