--- # Interactive playbook example
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.01b
  vars_prompt:
  - name: pkg
    prompt: Remove which package?
    private: no
    default: telnet
  tasks:
  - name: Remove the package
    yum: pkg={{ pkg }} state=removed
