--- #My First YAML playbook for ansible
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg
      prompt: pkg?
  tasks:
    - name: Removing APACHE Web Server
      yum: name=httpd state=removed
 #     notify: Restart HTTPD
    - name: Removing {{ pkg }} web browser
      action: yum name={{ pkg }} state=removed
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
      

