--- # Tag functionality example
- hosts: rpm
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install telnet and lynx
    yum: pkg={{ item }} state=removed
    with_items:
    - telnet
    - lynx
    tags:
    - packages
  - name: Verify telnet
    raw: yum list installed | grep telnet > /home/ansible/pkg.log
    tags:
    - verification
